import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/provider/theme-provider";
import { roboto, fraunces } from "./fonts";
import SmoothScrollProvider from "@/provider/smoothScrollProvider";
import { Header } from "@/components/layout/headerLayout";
import FooterLayout from "@/components/layout/footerLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${roboto.variable} ${fraunces.variable}`}
    >
      <body className="antialiased" suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SmoothScrollProvider>
            <Header />
            {children}
            <FooterLayout />
            </SmoothScrollProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
